export { default as Footer } from './Footer'
export { default as Navbar } from './Navbar'
export { default as Welcome } from './Welcome'
export { default as Contact } from './Contact'
export { default as PageNotFound } from './PageNotFound'
export { default as PrivacyPolicy } from './PrivacyPolicy'
export { default as HeroImg } from './HeroImg'
